/** @jsx h */
/// <reference no-default-lib="true"/>
/// <reference lib="dom" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />
import { h } from "https://crux.land/api/get/7GrKMy.ts";

export default () => {
	const svg =
	'data:image/svg+xml;base64,'+
	'PHN2ZyB3aWR0aD0iMzQwIiBoZWlnaHQ9IjQ1MCIgdmlld0JveD0iMCAwIDM0MCA0NTAiIGZpbGw9Im5vbmUiIHhtbG5zPS' +
	'JodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMCkiPgo8cGF0aCBkPSJNMTMx' +
	'LjY5OSAxOTIuNzI0QzEzMi4yMzUgMTkyLjcyNCAxMzIuNzcgMTkyLjcyMiAxMzMuMzA1IDE5Mi43MThDMTM0LjQzOSAxOT' +
	'UuNDE5IDEzNS42ODQgMTk5LjA3NSAxMzcuMDA2IDIwMy42OEMxMzguODc1IDIxMC4xODkgMTQwLjgwNSAyMTguMjUyIDE0' +
	'Mi43NjIgMjI3LjUyNEMxNDYuNjc2IDI0Ni4wNjIgMTUwLjY0NyAyNjkuMTggMTU0LjQyOSAyOTMuODY4QzE2MS45OTMgMz' +
	'QzLjIzMiAxNjguNzYzIDM5OC42MSAxNzIuNzkxIDQzNS42MTRMMTczLjU3NCA0NDIuODAzTDE4MC4zNzEgNDQwLjMzNUwz' +
	'MjUuOTI1IDM4Ny40ODFMMzMwLjc5MSAzODUuNzE0TDMyOS40NzggMzgwLjcwNkwyNTYuMTkyIDEwMS4xODlMMjUwLjg5MS' +
	'AxMDIuNTc5TDI1Ni4xOTIgMTAxLjE4OUMyNTMuNzkxIDkyLjAyOTEgMjQ5Ljg0NCA4My4yMTA3IDI0NS4zNTUgNzUuMjMx' +
	'NUMyMjguNzUxIDM2LjM2MzIgMTgzLjY5MSA5LjMyNDMyIDEzMS42OTkgOS4zMjQzMkM2Ni40MDI2IDkuMzI0MzIgMTEuMz' +
	'I0MyA1Mi4zMzQzIDExLjMyNDMgMTA3Ljc3MUMxMS4zMjQzIDEzNS42MDUgMjUuMzk4NSAxNTcuMDk3IDQ3LjUxNCAxNzEu' +
	'MzlDNjkuNDQ2OCAxODUuNTY1IDk5LjI4NzYgMTkyLjcyNCAxMzEuNjk5IDE5Mi43MjRaIiBmaWxsPSJ3aGl0ZSIgc3Ryb2' +
	'tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIxMS4zNTE0Ii8+CjxwYXRoIGQ9Ik0xNDUuMTkxIDgyLjQ3MjNDMTUyLjY0NCA4' +
	'Mi40NzIzIDE1OC42ODUgNzYuNDMwOSAxNTguNjg1IDY4Ljk3ODRDMTU4LjY4NSA2MS41MjU4IDE1Mi42NDQgNTUuNDg0NC' +
	'AxNDUuMTkxIDU1LjQ4NDRDMTM3LjczOSA1NS40ODQ0IDEzMS42OTcgNjEuNTI1OCAxMzEuNjk3IDY4Ljk3ODRDMTMxLjY5' +
	'NyA3Ni40MzA5IDEzNy43MzkgODIuNDcyMyAxNDUuMTkxIDgyLjQ3MjNaIiBmaWxsPSJibGFjayIvPgo8L2c+CjxkZWZzPg' +
	'o8Y2xpcFBhdGggaWQ9ImNsaXAwIj4KPHJlY3Qgd2lkdGg9IjM0MCIgaGVpZ2h0PSI0NTAiIGZpbGw9IndoaXRlIi8+Cjwv' +
	'Y2xpcFBhdGg+CjwvZGVmcz4KPC9zdmc+Cg=='
	return (
		<img src={svg} alt='Deno Logo' class="w-64"/>
	)
}